FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.26-openshift-5.1 AS builder
WORKDIR /go/src/github.com/openshift/azure-karpenter-provider
COPY . .
ENV BUILD_DEST=/go/bin/azure-karpenter-provider
RUN unset VERSION && make build

FROM registry.ci.openshift.org/ocp/5.1:base-rhel9
COPY --from=builder /go/bin/azure-karpenter-provider /usr/bin/

ENTRYPOINT ["/usr/bin/azure-karpenter-provider"]
